Repository koaning/scikit-lego, pull requests merged in 2025-04, with the labels that each got.

#736 fix: Allow to pickle/unpickle `DebugPipeline`
  sklego/pipeline.py
  tests/test_pipeline/test_debug_pipeline.py
Labels: fix

#738 feat: Add `stride_duration` in `TimeGapSplit`
  sklego/model_selection.py
  tests/test_model_selection/test_timegapsplit.py
Labels: enhancement

#743 chore: Bump ruff version
  .github/workflows/style.yml
  .pre-commit-config.yaml
  sklego/meta/thresholder.py
  sklego/pipeline.py
  tests/test_common/test_transformerselectormixin.py
  tests/test_pandas_utils/test_pandas_utils.py
  tests/test_pipeline/test_debug_pipeline.py
Labels: internal

#742 RFC, patch: fix `GroupTransformer` return dtype
  sklego/meta/grouped_transformer.py
  tests/test_meta/test_grouped_transformer.py
Labels: fix
